- src/Control/Foldl.hs
The new Prelude includes `mconcat `and `foldMap`, so the export list was declared ambiguous. Fortunately, since there is no ambiguous use within the file, this expedient
, Control.Foldl.mconcat
, Control.Foldl.foldMap
seems to work fine.
> Update for ghc-7.10

- src/Control/Foldl.hs
Add `Monad m => Profunctor (FoldM m)`
Remove unused `Monad m` context from `premapM`.
> Add Profunctor instance for (FoldM m)

- foldl.cabal
- src/Control/Foldl.hs
A Comonad instance for the Fold type.
**extract** closes the Fold without feeding any input.
**duplicate** lets you keep feeding values to a fold even after passing it to some function that "closes" it.
Pure example:
ghci> L.fold L.sum [1..100]
5050
ghci> L.fold (L.fold (duplicate L.sum) [1..50]) [51..100]
5050
Example in IO:
import System.IO
import Control.Monad (foldM)
import Control.Comonad
import qualified Control.Foldl as L
import qualified Pipes.Prelude as P
import qualified Pipes.ByteString as B
extract <$> foldM (\l f -> withFile f ReadMode $ L.purely P.fold (duplicate l) . B.fromHandle) 
L.list 
["file1.txt", "file2.txt"]
This commit adds a new direct dependency on **comonad** (**foldl** already depends transitively on **comonad**, by way of **profunctors**).
> Comonad instance for pure folds.

- src/Control/Foldl.hs
Hi,
Monadic folds can't be made instances of Comonad because they don't support a proper 'extract' function. But they can be duplicated in a similar manner to pure folds, and for similar purposes. I have added the 'duplicateM' function that does that.
Alternatively, they could be made instances of the [Data.Functor.Extend](http://hackage.haskell.org/package/semigroupoids-5.0.0.3/docs/Data-Functor-Extend.html#v:duplicated) (Comonad without extract) typeclass from the semigroupoids package. But adding that dependency for just one function is perhaps not worth it.
> Added "duplicateM" for monadic folds.

- src/Control/Foldl.hs
I recently needed the functionality of [`Data.List.maximumBy`](http://hackage.haskell.org/package/base-4.8.2.0/docs/Data-List.html#v:maximumBy). I actually got away with using tuple's `Ord` instance instead. But, I think it would be nice to have `maximumBy` and `minimumBy` in here.
> Added maximumBy and minimumBy

- src/Control/Foldl.hs
This makes the example at the beginning of Foldl.hs work correctly.
> `premap` needs to be qualified

- src/Control/Foldl.hs
Here is a little [criterion test](https://gist.github.com/michaelt/fd4db26b00d736421df6fab59c9566a4#file-test-hs) and the results for INLINABLE and INLINE.  In the criterion test, all hope of build/foldr and stream fusion is gone, so the test is rather plodding. I will append some results for the fusion cases elsewhere, but they are what got me thinking about it.
> INLINE Applicative and Functor implementations

- bench/benchmarks.hs
- foldl.cabal
Here are some results, compiled using GHC-8.0.1:
```
benchmarking [1..1000 :: Int]/sum/fold sum
mean                 7.769 μs   (7.767 μs .. 7.774 μs)
benchmarking [1..1000 :: Int]/sum/foldM (generalize sum)
mean                 5.381 μs   (5.380 μs .. 5.382 μs)
benchmarking [1..1000 :: Int]/sum/Prelude.sum
mean                 30.23 μs   (30.22 μs .. 30.24 μs)
benchmarking [1..1000 :: Int]/sum/Data.List.foldl' (+) 0
mean                 12.86 μs   (12.85 μs .. 12.87 μs)
```
```             
benchmarking [1..1000 :: Int]/filtered/fold (handles (filtered even) list)
mean                 26.44 μs   (26.42 μs .. 26.51 μs)
benchmarking [1..1000 :: Int]/filtered/foldM (handlesM (filtered even) (generalize list))
mean                 26.21 μs   (26.20 μs .. 26.22 μs)
benchmarking [1..1000 :: …
```
> Benchmarks (and some interesting results)

- src/Control/Foldl/ByteString.hs
- src/Control/Foldl/Text.hs
This PR adds `foldM` for `ByteString` and `Text`.
It is sometimes useful to run monadic computation on lazy `ByteString` or `Text`:
```haskell
ghci> LT.foldM (L.mapM_ print) $ TL.fromChunks ["foo", "bar", "baz"]
"foo"
"bar"
"baz"
```
> Add foldM for ByteString and Text

- .travis.yml
- src/Control/Foldl.hs
my first try at coupling Foldl and Lens, 
i'm not yet sure of the name and the runtime/space usage 
and not even sure if this cannot be replaced by `handles`, but in contrast to `handles`, `foldOfWith` can handle folds 
but i think that `foldOfWith f folder xs`  wil perform better than `L.fold folder (xs^..f)`
i think it should even be possible to add some kind of foldOfWithM
> FoldOfWith

- src/Control/Foldl.hs
It came into my head that `lookup` is a left fold, of a piece with `index`, `find` and so on. It is trivial but may be of interest as helping get beginners to see the range of things that can be represented as left folds.
> add lookup

- src/Control/Foldl.hs
`io-streams` now supports `purely` and `impurely` via `fold_` and `foldM_` 
See https://hackage.haskell.org/package/io-streams-1.3.6.0/docs/System-IO-Streams-Combinators.html#g:1  I modified the documentation of `purely` to bring this out. This maintains the idea of registering when libraries support `purely` unless there come to be more than a few, as was done with `mono-traversable`.  I'm not sure it's well worded, see what you think.
> note io-streams supports purely/impurely

- default.nix
- foldl.cabal
- src/Control/Foldl.hs
This improves the performance of the `vector` utility and allows it to become a
pure `Fold`
> Use `vector-builder`.  Fixes #88

- src/Control/Foldl.hs
This adds a small utility function that I use often: perform a fold while grouping the result according to a function.
> Added utility function `foldWithGroupBy`

- default.nix
- nix/fetchNixpkgs.nix
- nix/readDirectory.nix
- nix/turtle.nix
- release.nix
- shell.nix
This pins `nipxkgs` and also uses `readDirectory` to simplify testing changes
to dependencies
> Refactor Nix code

- src/Control/Scanl.hs
As discussed in issue #117, we have a new `scanr` function that reuses the original `Scan` type.
> Scanning from the right: `scanr`

- src/Control/Foldl.hs
The original version of mean is not numerically stable since the product x*n actually calculates the full sum in each update and it can be very large compared to y. The proposed version does not suffer from this problem. See [https://diego.assencio.com/?index=c34d06f4f4de2375658ed41f70177d59](url) for details.
> Change mean to be numerically stable.

- foldl.cabal
According to #107 support for base < 4.8 was dropped, but the cabal metadata
wasn't updated accordingly to reflect this
I've already revised the affected versions on Hackage as they were propagating build-plan failures into reverse dependencies
- https://hackage.haskell.org/package/foldl-1.4.1/revisions/
- https://hackage.haskell.org/package/foldl-1.4.2/revisions/
- https://hackage.haskell.org/package/foldl-1.4.3/revisions/
> Properly signal supported base versions

- bench/benchmarks.hs
- foldl.cabal
This adds the `sumAndLength` example from the documentation into the benchmarks. If run as follows `cabal new-run bench:benchmarks -- --regress allocated:iters` the relevant part of the output for the new benchmarks on my machine gives:
```
benchmarking [1..10000 :: Int]/sumAndLength/naive sumAndLength
time                 39.94 μs   (39.74 μs .. 40.20 μs)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 39.83 μs   (39.72 μs .. 40.03 μs)
std dev              508.2 ns   (333.0 ns .. 737.7 ns)
allocated:           1.000 R²   (1.000 R² .. 1.000 R²)
iters              103.989    (103.827 .. 104.187)
y                  2561.595   (2278.120 .. 2860.909)
benchmarking [1..10000 :: Int]/sumAndLength/foldl' sumAndLength
time                 43.58 μs   (43.09 μs .. 44.10 μs)
0.999 R²   (0.998 …
```
> Add documentation benchmarks

- foldl.cabal
- nix/foldl.nix
- src/Control/Foldl.hs
- test/doctest.hs
I set up a test-suite to run doctest while working on #140 and figured it might as well be part of the package?
I've also fixed a few things that doctest revealed to be failing. These fall into two categories:
- Names overlapping with `Prelude` that needed to be qualified
- References to things defined in `lens`; since that isn't a dependency, I just added a small `$setup` block which defines suitable replacements.
> Add test-suite for doctest, fix failing doctests

- src/Control/Foldl.hs
This adds `drop` and `dropM` proposed by #138. I also added a test suite to verify the two properties that I assert in the docs:
```haskell
L.fold (L.drop n folder) list = L.fold folder (Data.List.genericDrop n list)
L.foldM (L.dropM n folder) list = L.foldM folder (Data.List.genericDrop n list)
```
> Add drop and dropM

- src/Control/Foldl.hs
Adds two new functions, `foldByKeyMap` and `foldByKeyHashMap` which allow transforming a fold into a _parallel_ fold discriminated by a key. Happy to change the names to be more consistent.
```haskell
foldByKeyMap     :: forall k a b. Ord k              => Fold a b -> Fold (k, a) (Map k b)
foldByKeyHashMap :: forall k a b. (Hashable k, Eq k) => Fold a b -> Fold (k, a) (HashMap k b)
```
> Add foldByKey functions

- foldl.cabal
... which Hackage now requires for uploads
> Increase lower bound on `cabal`

- foldl.cabal
They are not needed on newer GHC.
> Depend on semigroups only on GHC < 8.0

- foldl.cabal
- src/Control/Foldl.hs
- src/Control/Foldl/Util/MVector.hs
- src/Control/Foldl/Util/Vector.hs
Builder provides more features than we need for which we have to pay with performance. In this PR I'm replacing it altogether with a simple and efficient strategy.
The strategy is to build it in two passes:
1. Accumulate a reverse list and its length.
2. Allocate a vector of that length and traverse it in reverse order populating it with elements of the list.
Performance of this function should now be comparable to the `list` fold.
> Reimplement immutable vector fold without builder

- foldl.cabal
Tested using 
```cabal
packages: .
constraints:
bytestring >= 0.11
source-repository-package
type: git
location: https://github.com/haskell/text
tag: v1.2.4.1-rc1
```
> Allow bytestring-0.11

- src/Control/Foldl.hs
Fixes #164
`HashMap` does not specify the order in which keys are returned, and
recent versions of `hashable` changed the order.  This change fixes
one of the doctests to not rely on that ordering by sorting the
result.
> Fix doctest failure

- src/Control/Foldl.hs
Because `Fold` is a `Comonad`, it's also an instance of [`Extend`](http://hackage.haskell.org/package/semigroupoids-5.3.5/docs/Data-Functor-Extend.html#v:duplicated) (from "semigroupoids").
`FoldM` is not a `Comonad` because we cant define `extract`, but it can be given an `Extend` instance. The implementation of [`duplicated`](http://hackage.haskell.org/package/semigroupoids-5.3.5/docs/Data-Functor-Extend.html#v:duplicated) is the same as the already-existing function `duplicateM`.
> Data.Functor.Extend instances for Fold and FoldM.

- foldl.cabal
- src/Control/Foldl.hs
`foldl` depends on `mwc-random`, but uses only `uniformR`, which is actually a re-export from `random`. Eliminating the middleman saves us three transitive dependencies: `mwc-random` itself + `math-functions` + `data-default-class`.
> Depend on random directly instead of mwc-random

- foldl.cabal
Related to https://github.com/commercialhaskell/stackage/issues/6624
> Build against `vector-0.13`

- src/Control/Foldl/NonEmpty.hs
https://github.com/Gabriella439/foldl/issues/183
> Add `Control.Foldl.NonEmpty.nonEmpty`

- foldl.cabal
`Choice` is not available from `Data.Profunctor` before `profunctors-3.2`.
As a Hackage trustee I made appropriate revisions for `foldl >= 1.4.5`.
> Require profunctors >= 3.2

- foldl.cabal
- src/Control/Foldl.hs
- stack.yaml
This is a PR which adds the instances, as mentioned in #197.
I decided not to add the `Corepresentable` instance, since it does rely on `cosieve . cotabulate` not being passed an infinite list.
Thus the `Costrong` instance simply inlines `unfirstCorep` as stated previously.
I also bumped the lts version to `lts-18.0`, since that is the earliest version which satisfies the `random >= 1.2.0` constraint (which also happens to satisfy the profunctors constraint).
> Cosieve and Costrong instances

- CHANGELOG.md
- bench/Foldl.hs
- foldl.cabal
- src/Control/Foldl.hs
- src/Control/Foldl/NonEmpty.hs
- test/doctest.hs
This change extends the API of `Control.Foldl.NonEmpty` by some of the exports suggested in #209:
- `Fold1_` pattern synonym
- `purely`
- `purely_`
- `premap`
- `handles`
- `foldOver`
- `folded1`
I created a naive [benchmark](https://github.com/Topsii/foldl/blob/335947515cd111ea687f6982d9bf48f615b5180b/bench/Foldl.hs#L59-L73) that compares the execution time of 
- `NonEmpty.map succ`
- variant that uses `Fold`
- variant that uses `FoldM`
- variant that uses the current definition `data Fold1 a b = forall x. Fold1 !(a -> x) !(x -> a -> x) !(x -> b)`  
imported qualified as `Foldl1`
- variant that uses the alternative definition `data Fold1 a b = Fold1 (a -> Fold a b)` from #209
imported qualified as `L1`
Note that the y-axis uses a logarithmic scale.
In this benchmark the current …
> Add Fold1 pattern synonym & utilities

- CHANGELOG.md
- src/Control/Foldl.hs
From the [docs ](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-Semigroup.html#v:stimesMonoid) of `stimesMonoid`:
> Unlike the default definition of [`stimes`](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-Semigroup.html#v:stimes), `stimesMonoid` is defined for 0 and so it should be preferred where possible.
> Define stimes 0 for EndoM

- CHANGELOG.md
- src/Control/Foldl.hs
- src/Control/Foldl/NonEmpty.hs
I omitted `Costrong` and `ArrowLoop` instances for Fold1.  Fold already has a `Costrong` instance, but similar to the Monad instances mentioned in https://github.com/Gabriella439/foldl/pull/214#issue-2636762695 I wonder whether it is safer to omit them to ensure Fold1s are streaming constant memory.
```haskell
instance Costrong Fold1 where
unfirst p = fmap f nonEmpty
where
f as = b
where
(b, d) = Control.Foldl.NonEmpty.fold1 p $ do
a <- as
pure (a, d)
instance ArrowLoop Fold1 where
loop = unfirst
```
I also added `nest` for Fold1 and distinguished between both and both1 in the doctests.
> Add more Fold1 instances

- CHANGELOG.md
- src/Control/Foldl.hs
Adds `lifts`, which is similar to `Control.Monad.Trans.Class.lift`. You could define a Monad instance for FoldM such that
```
lifts (m >>= f) = lifts m >>= (lifts . f)
```
```haskell
instance Monad (Fold a) where
return = pure
m >>= f = fold . f <$> m <*> list
instance Monad m => Monad (FoldM m a) where
return = pure
m >>= f = postmapM id $ foldM . f <$> m <*> generalize list
```
We already have `hoists`, which is similar to `Control.Monad.Morph.hoist`.
You can also define `embeds` and `squashes`, similar to `Control.Monad.Morph.embed` and `Control.Monad.Morph.squash`, respectively, satisfying (I believe)
```
embeds lifts = id
embeds f (lifts m) = f m
```
```haskell
embeds :: Monad n => (forall x. m x -> FoldM n a x) -> FoldM m a b -> FoldM n a b
embeds f fld = squashes $ hoists f fld …
```
> Fix postmapM law by adding lifts

- CHANGELOG.md
- src/Control/Foldl/NonEmpty.hs
```haskell
*> L1.fold1 (arr $ left id) (Right 10 :| [Left 200 :: Either Int Int])                     
Left 200
*> L1.fold1 (left $ arr id) (Right 10 :| [Left 200 :: Either Int Int]) 
Right 10
```
violates the [ArrowChoice law](https://hackage.haskell.org/package/base-4.18.1.0/docs/Control-Arrow.html#t:ArrowChoice) that `left (arr f) = arr (left f)`.
When I added this instance in #215 I was trusting that the [ArrowChoice instance](https://github.com/ekmett/folds/blob/f24f34e0ac82d0dac2051faef4aad2b4e85a0f15/src/Data/Fold/L1'.hs#L141-L152) that already existed in the [folds package](https://hackage.haskell.org/package/folds) was correct. I apologize for any inconvenience.
> Remove unlawful ArrowChoice instance
