Gabriella439/foldl

src/Control/Foldl.hs
The name seems odd, but I couldn't find a better one.
=> Added `mkFold1`

foldl.cabal, src/Control/Foldl.hs
=> instantiated `Profunctor` for `Fold`

src/Control/Foldl.hs
I've added an example for those not too familiar with the full power of the Applicative interface.
=> Documenting an example using Data.Traversable

src/Control/Foldl.hs
=> Added mapM_

src/Control/Foldl.hs
I assume that these pragmas were left out by accident, not intentionally.
=> Add a few missing INLINABLE pragmas

bench/benchmarks.hs, foldl.cabal, src/Control/Foldl.hs
This one adds new dependencies, but then they are de-facto standard.
=> Unordered containers

src/Control/Foldl.hs
Sometimes it's convenient to use foldl without a `lens` library and still be able to use filtering Folds.
prefilter(M) are very easy to define without `handles`, that's why I'm proposing to add them.
It also makes IMHO `foldl` even more more accessible to Haskell newcomers since they don't have to worry about the dreaded lenses to use filtering Folds.
=> Added prefilter and prefilterM

src/Control/Foldl.hs
=> Expand documentation for `prefilter` and `prefilterM`

src/Control/Foldl.hs
Now that we dropped pre AMP GHC, we can do this! I'll rebase my scan changes on top.
=> Relax some constraints and get rid of CPP

foldl.cabal, src/Control/Foldl.hs, src/Control/Foldl/Internal.hs, src/Control/Scanl.hs
=> WIP support for Scan

foldl.cabal, src/Control/Foldl.hs
=> Add instance Semigroupoid Fold

src/Control/Scanl.hs
=> Document difference between `Scan` and `Fold` types

src/Control/Foldl.hs
As discussed in #144. 
I added it in the "utility" section of `Control/Foldl.hs`.
I'm not sure if I should add any of INLINE or INLINABLE pragma.
=> Add `nest` fold.

foldl.cabal
Related to https://github.com/commercialhaskell/stackage/issues/5557
=> Build against `mwc-random-0.15.0.0`

foldl.cabal
Related to https://github.com/commercialhaskell/stackage/issues/5667
=> Build against `profunctors-5.6`

foldl.cabal
https://hackage.haskell.org/package/text-2.0/changelog
=> Allow text-2.0

cabal.project, foldl.cabal
=> Allow transformers 0.6

foldl.cabal, src/Control/Foldl/NonEmpty.hs
Fixes https://github.com/Gabriella439/foldl/issues/177
=> Add new "Control.Foldl.NonEmpty" module

src/Control/Foldl/NonEmpty.hs
Fixes https://github.com/Gabriella439/foldl/issues/184
=> Generalize `fold1` to work with `Foldable1`

src/Control/Foldl.hs
=> Remove erroneous prefilterM documentation

src/Control/Foldl/NonEmpty.hs
Fixes https://github.com/Gabriella439/foldl/issues/190
=> Add `Control.Foldl.NonEmpty.toFold`

foldl.cabal
Related to https://github.com/commercialhaskell/stackage/issues/6909
=> Build against `semigroupoids-6`

CHANGELOG.md, foldl.cabal, src/Control/Foldl.hs
Added postmapM. I think I documented it correctly!
=> Added postmapM; bumped cabal version; added to changelog
